### ISSUE TITLE
Linkable waypoints in chat box

### ISSUE THREAD

**Issue by Sillysith** [KyrosKrane/DrillSergeant#3]
Could we get waypoints in chat to be "linkable" to guide us to the location the way TomTom is done please? As of right now, DrillSergeant displays the waypoint but it is not a link in the Chatbox.

Thank you for your work on this project!

**Comment by KyrosKrane** [comment]
This might be possible. Most likely, I would require Tomtom to be installed separately, and throw up a Tomtom arrow to the location when you click the link in chat. I’ll have to make sure the rares don’t wander or have multiple spawn points - it’s been a while since I puttered around Mechagon. I’m away from the game for a few days, but I’ll see about adding this later.

**Comment by Sillysith** [comment]
Thank you for your response. Like I mentioned before, the waypoints drillsergeant put in chat are not clickable. Would be nice if they were. Great addon btw!

**Comment by KyrosKrane** [comment]
So, first pass at this is in v1.3.0-release. I made the loc clickable using the built-in waypoints for the game. Check it out and let me know what you think.

In a future release, I'll consider how to make it work with Tomtom.

**Comment by Sillysith** [comment]
Any success?

**Comment by KyrosKrane** [comment]
Initial code changes to enable TomTom support are in v2 alpha builds, code is in the TomTom branch, if you want to experiment with it.

**Comment by KyrosKrane** [comment]
This is now a feature in v2.0.0, which should be available momentarily at the usual download sites.
